controllerServiceAccount:
  name: arc-runner-set
  namespace: arc-runners
containerMode:
  type: dind

template:
  spec:
    containers:
      - name: runner
        resources:
          limits:
            cpu: 16
            memory: 32Gi
          requests:
            cpu: 48
            memory: 196Gi