controllerServiceAccount:
  name: asdf
  namespace: asdf
containerMode:
  type: dind
githubConfigUrl: asdf
githubConfigSecret:
  github_token: asdf
controllerServiceAccount:
  name: asdf
  namespace: asdf